### basic settings

# site properties and page defaults
title: Dementia Informatics Laboratory
description: Our lab website
logo: images/logo.jpg
header: images/backgroundtop.png
footer: images/backgroundtop.png
baseurl: /website_rittman_lab

# site social media and other links
links:
  email: tr332@medschl.cam.ac.uk
  google-scholar: Tim Rittman
  github: to-add
  twitter: to-add

### other settings

# in progress potential automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # markdown files in /_tools
  - scope:
      type: "tools"
    values:
      layout: tools

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
